### ISSUE TITLE
Bugs Bugs Bugs

### ISSUE THREAD

**Issue by BurrowIsPog** [SomePineaple/PineapleClient#11]
Instant Burrow
Burrow
Blink

**Comment by phobologicalt** [comment]
momentum has a working burrow and its open src and why do you need blink kek

**Comment by MMHKGamerpro12** [comment]
i accident click blink and if i disable it the client crash

**Comment by SomePineaple** [comment]
fixed blink, im not really bothered about burrow, i don't use it much, and btw it does kinda work.
