### ISSUE TITLE
How Do I add modules to wurstplustwo

### ISSUE THREAD

**Issue by jraffstar** [SomePineaple/PineapleClient#12]
I wanna make trash skid 👀

**Comment by SomePineaple** [comment]
Create a new class extending the Hack class in one of the different packages for the different types of modules, for example if you want to make  a combat hack, put it in the combat package. Create a constructor that calls super and passes in the category of hack you want to make. Then in the constructor add
```
this.name = "My Hack";
this.tag = "MyHack";
this.description = "Does new cool feature";
```
Then you can override the update method and put things in there that you want to do every tick. Finally to register it w/ the client, you have to go to `ModuleManager.java` in the `managers` package, go to the constructor and call `add_hack(new MyHack());`
