### ISSUE TITLE
Client crashes 

### ISSUE THREAD

**Issue by citrousleafgame** [SomePineaple/PineapleClient#5]
So i put the mod in my mods folder and tried to launch the game and it crashes. Please help i really wanna use this client

**Comment by citrousleafgame** [comment]
Update: The first version of the client works fine but others dont

**Comment by TalentedToad** [comment]
@citrousleafgame its because 1 of your clients are not compatible with client so you need to remove the one causing problems

**Comment by SomePineaple** [comment]
Try compiling it yourself and see if it works then.

**Comment by phobologicalt** [comment]
build latest

**Comment by SomePineaple** [comment]
closing old issue, if u still need help re-open
